pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}
ext {
    localMavenRepo = file("$settingsDir/local-maven")
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        maven {
            url localMavenRepo.absolutePath
        }
        maven {
            url = uri("https://central.sonatype.com/repository/maven-snapshots/")
            content {
                includeGroup("org.lynxsdk.lynx")
            }
        }
        mavenCentral()
        google()
    }
}

rootProject.name = "JavaEmptyProject"
include ':app'
