PRIVATE_SPECS = 'https://github.com/lynx-family/Specs.git'
TRUNK_SPECS = 'https://cdn.cocoapods.org/'

source PRIVATE_SPECS
source TRUNK_SPECS

platform :ios, '10.0'

target 'Hello-Lynx' do
  pod 'Lynx', '4.1.0',
      :source => PRIVATE_SPECS,
      :subspecs => [
    'Framework',
  ]

  pod 'PrimJS', '4.1.1', :subspecs => ['quickjs', 'napi']

  # integrate image-service, log-service, and http-service
  pod 'LynxService', '4.1.0',
      :source => PRIVATE_SPECS,
      :subspecs => [
      'Image',
      'Log',
      'Http',
  ]

  # ImageService dependencies:
  pod 'SDWebImage','5.15.5'
  pod 'SDWebImageWebPCoder', '0.11.0'

  # XElement
  pod 'XElement', '4.1.0',
      :source => PRIVATE_SPECS
end
