source 'https://cdn.cocoapods.org/'

platform :ios, '10.0'

target 'Hello-Lynx' do
  pod 'Lynx', '4.0.0', :subspecs => [
    'Framework',
  ]

  pod 'PrimJS', '4.0.0', :subspecs => ['quickjs', 'napi']

  # integrate image-service, log-service, and http-service
  pod 'LynxService', '4.0.0', :subspecs => [
      'Image',
      'Log',
      'Http',
  ]

  # ImageService dependencies:
  pod 'SDWebImage','5.15.5'
  pod 'SDWebImageWebPCoder', '0.11.0'

  # XElement
  pod 'XElement', '4.0.0'
end
