# # Uncomment the next line to define a global platform for your project
# # platform :ios, '9.0'

# target 'Hello-Lynx-OC' do
#   # Comment the next line if you don't want to use dynamic frameworks
#   use_frameworks!

#   # Pods for Hello-Lynx-OC

# end

source 'https://cdn.cocoapods.org/'

platform :ios, '9.0'

target 'Hello-Lynx-OC' do
  pod 'Lynx', '~> 3.2.0-alpha.1', :subspecs => [
    'Framework',
  ]

  pod 'PrimJS', '~> 2.11.1-alpha.3', :subspecs => ['quickjs', 'napi']

  # integrate image-service, log-service, and http-service
  pod 'LynxService', '3.2.0-alpha.1', :subspecs => [
      'Image',
      'Log',
      'Http',
  ]

  # ImageService
  pod 'SDWebImage','5.15.5'
  pod 'SDWebImageWebPCoder', '0.11.0'
end