# # Uncomment the next line to define a global platform for your project
# # platform :ios, '9.0'

# target 'Hello-Lynx-OC' do
#   # Comment the next line if you don't want to use dynamic frameworks
#   use_frameworks!

#   # Pods for Hello-Lynx-OC

# end

PRIVATE_SPECS = 'https://github.com/lynx-family/Specs.git'
TRUNK_SPECS = 'https://cdn.cocoapods.org/'

source PRIVATE_SPECS
source TRUNK_SPECS

platform :ios, '10.0'

target 'Hello-Lynx-OC' do

  pod 'Lynx', '4.1.0',
      :source => PRIVATE_SPECS,
      :subspecs => [
        'Framework',
      ]

  pod 'PrimJS', '4.1.1', :subspecs => [
    'quickjs',
    'napi',
  ]

  pod 'LynxService', '4.1.0',
      :source => PRIVATE_SPECS,
      :subspecs => [
        'Image',
        'Log',
        'Http',
      ]

  pod 'SDWebImage', '5.15.5'
  pod 'SDWebImageWebPCoder', '0.11.0'

  pod 'XElement', '4.1.0',
      :source => PRIVATE_SPECS
end
